// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSQqLab9H0mrGXtxN_ksc7N62LBzGtm5o',
    appId: '1:1043955780629:web:ff53d06954cbb66121521c',
    messagingSenderId: '1043955780629',
    projectId: 'pomodoro-timer-database',
    authDomain: 'pomodoro-timer-database.firebaseapp.com',
    storageBucket: 'pomodoro-timer-database.appspot.com',
    measurementId: 'G-B4TPZ8D5WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP4PLbtZ4C_QATxTLZPVqEO3-tA1oHQSg',
    appId: '1:1043955780629:android:39e140b4d2ff992321521c',
    messagingSenderId: '1043955780629',
    projectId: 'pomodoro-timer-database',
    storageBucket: 'pomodoro-timer-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIGFa8tPW7oz31jiFd9xaz18cAg239Ueo',
    appId: '1:1043955780629:ios:799ba9fe5d8a248a21521c',
    messagingSenderId: '1043955780629',
    projectId: 'pomodoro-timer-database',
    storageBucket: 'pomodoro-timer-database.appspot.com',
    iosClientId: '1043955780629-u126f4at97kek6ii7tjg6lkehmsi3d5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomodoroTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIGFa8tPW7oz31jiFd9xaz18cAg239Ueo',
    appId: '1:1043955780629:ios:9cba43d6f81450a721521c',
    messagingSenderId: '1043955780629',
    projectId: 'pomodoro-timer-database',
    storageBucket: 'pomodoro-timer-database.appspot.com',
    iosClientId: '1043955780629-cdjbc6b9sn2ua06v2oc31bmsqbadfnt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomodoroTimer.RunnerTests',
  );
}
